name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v2 

    - name: Install
      uses: pandoc/actions/setup@{main}
      with:
        version: 3.1.8

    - name: Run script from the scripts folder
      run: |
        chmod +x ./scripts/transform_files.sh 
        ./scripts/transform_files.sh 

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

